// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Возвращает ok, если HTTP-сервер запущен. Не требует авторизации.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "probes"
                ],
                "summary": "Проверка живости",
                "responses": {
                    "200": {
                        "description": "Сервер работает",
                        "schema": {
                            "$ref": "#/definitions/internal_core_transport_http_probes.ProbeStatusResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Возвращает ready, если PostgreSQL доступен. Не требует авторизации.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "probes"
                ],
                "summary": "Проверка готовности",
                "responses": {
                    "200": {
                        "description": "Приложение готово принимать запросы",
                        "schema": {
                            "$ref": "#/definitions/internal_core_transport_http_probes.ProbeStatusResponse"
                        }
                    },
                    "503": {
                        "description": "База данных недоступна",
                        "schema": {
                            "$ref": "#/definitions/internal_core_transport_http_probes.ProbeStatusResponse"
                        }
                    }
                }
            }
        },
        "/statistics": {
            "get": {
                "description": "Агрегированная статистика по задачам. Параметр user_id опционален: без него — по всем пользователям.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Статистика",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Фильтр по пользователю",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Начало периода (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Конец периода (YYYY-MM-DD, не включая этот день)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Статистика",
                        "schema": {
                            "$ref": "#/definitions/internal_features_statistics_transport_http.GetStatisticsResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный период или параметры",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "Возвращает задачи. Можно отфильтровать по user_id. Поддерживает пагинацию limit/offset (по умолчанию limit=50, max=100).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Список задач",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Фильтр по автору",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список задач",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_tasks_transport_http.TaskDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Невалидные параметры",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт новую задачу с указанным автором (author_user_id).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Создать задачу",
                "parameters": [
                    {
                        "description": "Данные новой задачи",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Задача создана",
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.CreateTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидные данные",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "Возвращает задачу по её идентификатору.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Получить задачу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные задачи",
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.GetTaskResponse"
                        }
                    },
                    "404": {
                        "description": "Задача не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "tasks"
                ],
                "summary": "Удалить задачу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Задача удалена"
                    },
                    "404": {
                        "description": "Задача не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Частичное обновление. При completed=true автоматически проставляется completed_at.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Изменить задачу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Поля для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.PatchTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённая задача",
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.PatchTaskUserResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидные данные",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Задача не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Возвращает всех пользователей. Поддерживает пагинацию limit/offset (по умолчанию limit=50, max=100).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Список пользователей",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Размер страницы",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список пользователей",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_users_transport_http.UserDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Невалидные параметры",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Регистрирует нового пользователя. Телефон опционален.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать пользователя",
                "parameters": [
                    {
                        "description": "Данные нового пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь создан",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидные данные",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Возвращает данные пользователя по его идентификатору.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные пользователя",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.GetUserResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет пользователя по id. Если есть связанные задачи, может вернуться 409.",
                "tags": [
                    "users"
                ],
                "summary": "Удалить пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пользователь удалён"
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Конфликт (например, есть связанные данные)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Частичное обновление профиля пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Изменить пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Поля для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.PatchUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённый профиль",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.PatchUserResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидные данные",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Slazzzer_golang-todoapp_internal_core_transport_http_types.Nullable-bool": {
            "type": "object",
            "properties": {
                "set": {
                    "type": "boolean"
                },
                "value": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Slazzzer_golang-todoapp_internal_core_transport_http_types.Nullable-string": {
            "type": "object",
            "properties": {
                "set": {
                    "type": "boolean"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "internal_core_transport_http_probes.ProbeStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Статус: ok, ready или not ready",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_features_statistics_transport_http.GetStatisticsResponse": {
            "type": "object",
            "properties": {
                "task_completed_rate": {
                    "description": "Процент завершённых (0–100) или null",
                    "type": "number",
                    "example": 70
                },
                "tasks_average_completion_time": {
                    "description": "Среднее время выполнения или null",
                    "type": "string",
                    "example": "24h30m15s"
                },
                "tasks_completed": {
                    "description": "Завершено задач за период",
                    "type": "integer",
                    "example": 7
                },
                "tasks_created": {
                    "description": "Создано задач за период",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "internal_features_tasks_transport_http.CreateTaskRequest": {
            "type": "object",
            "required": [
                "author_user_id",
                "title"
            ],
            "properties": {
                "author_user_id": {
                    "description": "ID автора задачи",
                    "type": "integer",
                    "example": 1
                },
                "description": {
                    "description": "Описание (опционально)",
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1,
                    "example": "2 литра"
                },
                "title": {
                    "description": "Заголовок (1–100 символов)",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Купить молоко"
                }
            }
        },
        "internal_features_tasks_transport_http.CreateTaskResponse": {
            "type": "object",
            "properties": {
                "author_user_id": {
                    "description": "ID автора (из JWT)",
                    "type": "integer",
                    "example": 1
                },
                "completed": {
                    "description": "Выполнена ли задача",
                    "type": "boolean",
                    "example": false
                },
                "completed_at": {
                    "description": "Дата завершения или null",
                    "type": "string"
                },
                "created_at": {
                    "description": "Дата создания",
                    "type": "string",
                    "example": "2026-07-08T12:00:00Z"
                },
                "description": {
                    "description": "Описание или null",
                    "type": "string",
                    "example": "2 литра"
                },
                "id": {
                    "description": "Идентификатор задачи",
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "description": "Заголовок",
                    "type": "string",
                    "example": "Купить молоко"
                },
                "version": {
                    "description": "Версия записи",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_tasks_transport_http.GetTaskResponse": {
            "type": "object",
            "properties": {
                "author_user_id": {
                    "description": "ID автора (из JWT)",
                    "type": "integer",
                    "example": 1
                },
                "completed": {
                    "description": "Выполнена ли задача",
                    "type": "boolean",
                    "example": false
                },
                "completed_at": {
                    "description": "Дата завершения или null",
                    "type": "string"
                },
                "created_at": {
                    "description": "Дата создания",
                    "type": "string",
                    "example": "2026-07-08T12:00:00Z"
                },
                "description": {
                    "description": "Описание или null",
                    "type": "string",
                    "example": "2 литра"
                },
                "id": {
                    "description": "Идентификатор задачи",
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "description": "Заголовок",
                    "type": "string",
                    "example": "Купить молоко"
                },
                "version": {
                    "description": "Версия записи",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_tasks_transport_http.PatchTaskRequest": {
            "type": "object",
            "properties": {
                "completed": {
                    "description": "Статус выполнения (опционально)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Slazzzer_golang-todoapp_internal_core_transport_http_types.Nullable-bool"
                        }
                    ]
                },
                "description": {
                    "description": "Новое описание (опционально)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Slazzzer_golang-todoapp_internal_core_transport_http_types.Nullable-string"
                        }
                    ]
                },
                "title": {
                    "description": "Новый заголовок (опционально)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Slazzzer_golang-todoapp_internal_core_transport_http_types.Nullable-string"
                        }
                    ]
                }
            }
        },
        "internal_features_tasks_transport_http.PatchTaskUserResponse": {
            "type": "object",
            "properties": {
                "author_user_id": {
                    "description": "ID автора (из JWT)",
                    "type": "integer",
                    "example": 1
                },
                "completed": {
                    "description": "Выполнена ли задача",
                    "type": "boolean",
                    "example": false
                },
                "completed_at": {
                    "description": "Дата завершения или null",
                    "type": "string"
                },
                "created_at": {
                    "description": "Дата создания",
                    "type": "string",
                    "example": "2026-07-08T12:00:00Z"
                },
                "description": {
                    "description": "Описание или null",
                    "type": "string",
                    "example": "2 литра"
                },
                "id": {
                    "description": "Идентификатор задачи",
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "description": "Заголовок",
                    "type": "string",
                    "example": "Купить молоко"
                },
                "version": {
                    "description": "Версия записи",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_tasks_transport_http.TaskDTOResponse": {
            "type": "object",
            "properties": {
                "author_user_id": {
                    "description": "ID автора (из JWT)",
                    "type": "integer",
                    "example": 1
                },
                "completed": {
                    "description": "Выполнена ли задача",
                    "type": "boolean",
                    "example": false
                },
                "completed_at": {
                    "description": "Дата завершения или null",
                    "type": "string"
                },
                "created_at": {
                    "description": "Дата создания",
                    "type": "string",
                    "example": "2026-07-08T12:00:00Z"
                },
                "description": {
                    "description": "Описание или null",
                    "type": "string",
                    "example": "2 литра"
                },
                "id": {
                    "description": "Идентификатор задачи",
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "description": "Заголовок",
                    "type": "string",
                    "example": "Купить молоко"
                },
                "version": {
                    "description": "Версия записи",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_users_transport_http.CreateUserRequest": {
            "type": "object",
            "required": [
                "full_name"
            ],
            "properties": {
                "full_name": {
                    "description": "Полное имя (3–100 символов)",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Иван Иванов"
                },
                "phone_number": {
                    "description": "Телефон в формате +7... (опционально)",
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10,
                    "example": "+79991234567"
                }
            }
        },
        "internal_features_users_transport_http.CreateUserResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Полное имя",
                    "type": "string",
                    "example": "Иван Иванов"
                },
                "id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer",
                    "example": 1
                },
                "phone_number": {
                    "description": "Телефон или null",
                    "type": "string",
                    "example": "+79991234567"
                },
                "version": {
                    "description": "Версия записи (для оптимистичной блокировки)",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_users_transport_http.GetUserResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Полное имя",
                    "type": "string",
                    "example": "Иван Иванов"
                },
                "id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer",
                    "example": 1
                },
                "phone_number": {
                    "description": "Телефон или null",
                    "type": "string",
                    "example": "+79991234567"
                },
                "version": {
                    "description": "Версия записи (для оптимистичной блокировки)",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_users_transport_http.PatchUserRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Новое полное имя (опционально)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Slazzzer_golang-todoapp_internal_core_transport_http_types.Nullable-string"
                        }
                    ]
                },
                "phone_number": {
                    "description": "Новый телефон (опционально, null — удалить)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Slazzzer_golang-todoapp_internal_core_transport_http_types.Nullable-string"
                        }
                    ]
                }
            }
        },
        "internal_features_users_transport_http.PatchUserResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Полное имя",
                    "type": "string",
                    "example": "Иван Иванов"
                },
                "id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer",
                    "example": 1
                },
                "phone_number": {
                    "description": "Телефон или null",
                    "type": "string",
                    "example": "+79991234567"
                },
                "version": {
                    "description": "Версия записи (для оптимистичной блокировки)",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_users_transport_http.UserDTOResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Полное имя",
                    "type": "string",
                    "example": "Иван Иванов"
                },
                "id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer",
                    "example": 1
                },
                "phone_number": {
                    "description": "Телефон или null",
                    "type": "string",
                    "example": "+79991234567"
                },
                "version": {
                    "description": "Версия записи (для оптимистичной блокировки)",
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5050",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Todoapp API",
	Description:      "REST API для todo-приложения (задачи, пользователи, статистика).\nОткрытый API без авторизации: все эндпоинты доступны под /api/v1.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
